views:
  - id: watermeter_report
    icon: 'mdi:water-well-outline'
    panel: true
    path: watermeter
    cards:
      - type: 'custom:cards-layout'
        toolbar:
          backgroundcolor: '#D0EDF5'
          iconcolor: '#1AB0F4'
          visible: true
        header:
          title: Wasserverbrauch
          icon: 'mdi:water-well-outline'
          iconcolor: '#1AB0F4'
          style: >-
            background-image:
            url('/hacsfiles/cards-layout/assets/ha-header-bathroom.png');
            background-color: #D0EDF5; color: #1AB0F4;
        page:
          title: Übersicht
          icon: 'mdi:waves'
          description: Austellung Wasserverbauch
          width: 95%
          style: >-
            color:"#FFFFFF"; background: linear-gradient(to top,
            #0C47A1,#03A9F4);
        content:
          - row:
              - columns: null
                title: Auswertung Wasserverbrauch
                width: 100%
                entities:
                  - type: 'custom:chart-card'
                    title: Wasserverbrauch ㎥ / Tag
                    icon: 'mdi:counter'
                    height: 360
                    chart: line
                    debug: true
                    showstate: true
                    showdetails:
                      title_sensor: Messwert
                      title_mean: Durchschnitt / Tag
                      title_max: Größter Wert
                      title_current: Letzter Wert
                      visible: true
                    datascales:
                      mode: time
                    chartOptions:
                      plugins:
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          grid:
                            display: false
                        'y':
                          suggestedMin: 0
                          suggestedMax: 8
                          grid:
                            display: true
                          title:
                            display: true
                            text: Verbrauch ㎥
                    entities:
                      - entity: sensor.date_time
                        dataid: wasser
                        unit: ㎥
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=home_assistant&epoch=ms
                          query: >-
                            SELECT sum("value") FROM "㎥" WHERE ("entity_id" =
                            'max_m3_day') AND time > now() -180d GROUP BY
                            time(1d) fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Wasserverbrauch
                        style:
                          backgroundColor: 'rgba(58,165,231,0.75)'
                          fill: true
                          borderWidth: 1
                          order: 1
                  - type: 'custom:chart-card'
                    title: Ausschöpfungsrate
                    icon: 'mdi:waves'
                    height: 360
                    chart: bar
                    showstate: true
                    chartOptions:
                      segmented: true
                      scales:
                        x:
                          grid:
                            display: false
                        'y':
                          suggestedMin: 0
                          suggestedMax: 100
                          grid:
                            display: true
                          title:
                            display: true
                            text: Rate in %
                    entities:
                      - options:
                          unit: '%'
                          borderSkipped: false
                          backgroundColor: '#3aa5e7'
                          borderRadius:
                            bottomRight: 25
                            bottomLeft: 25
                      - entity: sensor.wasser_liter_h
                        name: Stunde
                        target_value: 100
                        style:
                          backgroundColor: '#3aa5e7'
                      - entity: sensor.wasser_liter_tag
                        name: Tag
                        target_value: 350
                        style:
                          backgroundColor: '#3aa5e7'
                      - entity: sensor.wasser_liter_monat
                        name: Monat
                        target_value: 6500
                        style:
                          backgroundColor: '#3aa5e7'
                      - entity: sensor.wasser_liter_jahr
                        name: Jahr
                        target_value: 75000
                        style:
                          backgroundColor: '#3aa5e7'
          - row:
              - columns: null
                title: Übersicht Wasserverbrauch
                width: 50%
                entities:
                  - type: 'custom:chart-card'
                    title: Wasserverbrauch / Stunde
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    showstate: true
                    datascales:
                      range: 48
                      unit: hour
                      mode: category
                    showdetails:
                      title: Zusammenfassung
                      title_sensor: Verbrauch
                      title_mean: Mittelwert
                      title_min: Min.
                      title_max: Max.
                      title_current: Aktuell
                      visible: true
                    chartOptions:
                      scales:
                        x:
                          grid:
                            display: false
                        'y':
                          grid:
                            display: true
                          title:
                            display: true
                            text: Liter
                    entities:
                      - entity: sensor.wasser_liter_h
                        name: Aktuell
                        aggregate: max
                        style:
                          backgroundColor: '#1AB0F4'
                  - type: 'custom:chart-card'
                    title: Wasserverbrauch / Tag
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    showstate: true
                    datascales:
                      range: 192
                      unit: day
                      mode: category
                    showdetails:
                      title: Zusammenfassung
                      title_sensor: Verbrauch
                      title_mean: Mittelwert
                      title_min: Min.
                      title_max: Max.
                      title_current: Aktuell
                      visible: true
                    chartOptions:
                      scales:
                        x:
                          grid:
                            display: false
                        'y':
                          grid:
                            display: true
                          title:
                            display: true
                            text: Liter
                    entities:
                      - entity: sensor.wasser_liter_tag
                        name: Tagesverbrauch
                        aggregate: last
                        style:
                          backgroundColor: '#1AB0F4'
          - row:
              - columns: null
                title: Details zu Wasserverbrauch & - Kosten
                width: 100%
                entities:
                  - type: 'custom:homekit-card'
                    useBrightness: false
                    titleColor: '#fff'
                    enableColumns: false
                    statePositionTop: true
                    home: false
                    style: |
                      .card-title {
                        font-size: 1.25em !important;
                        line-height: 3em !important;
                        padding-top: 18px !important;
                      }
                      .name {
                        font-size: 0.90em !important;
                      }
                      .state{
                        overflow: hidden !important;
                        text-overflow: ellipsis !important;
                      }
                    tap_action:
                      action: more-info
                    entities:
                      - title: Wasserverbrauch
                        entities:
                          - entity: sensor.wasseraktuell_liter
                            name: zur Zeit
                            tap_action:
                              action: more-info
                              entity: sensor.wasseraktuell_liter
                          - entity: sensor.wasser_liter_h
                            name: Jetzt
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_liter_h
                          - entity: sensor.wasser_liter_tag
                            name: Heute
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_liter_tag
                          - entity: sensor.wasser_liter_monat
                            name: Monat
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_liter_monat
                          - entity: sensor.wasser_liter_jahr
                            name: Jahr
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_liter_jahr
                      - title: Wasser Kosten
                        entities:
                          - entity: sensor.water_cost_current
                            name: zur Zeit
                            tap_action:
                              action: more-info
                              entity: sensor.water_cost_current
                          - entity: sensor.water_cost_hour
                            name: Jetzt
                            tap_action:
                              action: more-info
                              entity: sensor.water_cost_hour
                          - entity: sensor.water_cost_day
                            name: Heute
                            tap_action:
                              action: more-info
                              entity: sensor.water_cost_day
                          - entity: sensor.water_cost_month
                            name: Monat
                            tap_action:
                              action: more-info
                              entity: sensor.water_cost_month
                          - entity: sensor.water_cost_jahr
                            name: Jahr
                            tap_action:
                              action: more-info
                              entity: sensor.water_cost_jahr
                      - title: Wasserzähler Anzeige
                        entities:
                          - entity: sensor.wasserzahler_aktuell
                            name: Gesamt m³
                            tap_action:
                              action: more-info
                              entity: sensor.wasserzahler_aktuell
                          - entity: sensor.wasser_pro_monat
                            name: m³/Monat
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_pro_monat
                          - entity: sensor.wasser_pro_jahr
                            name: m³/Jahr
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_pro_jahr
                          - entity: sensor.wasserzahler_status
                            name: Status
                            tap_action:
                              action: more-info
                              entity: sensor.wasserzahler_status
                          - entity: sensor.wasser_alarm
                            name: Alarm
                            tap_action:
                              action: more-info
                              entity: sensor.wasser_alarm
