views:
  - title: Energie Report
    icon: 'mdi:counter'
    id: energie_report
    panel: true
    path: energiereport
    cards:
      - type: 'custom:cards-layout'
        toolbar:
          backgroundcolor: '#366484'
          iconcolor: '#FFFFFF'
          visible: true
        header:
          title: Stromverbrauch & -Produktion
          icon: 'mdi:counter'
          iconcolor: '#FFFFFF'
          style: >-
            background-image:
            url('/hacsfiles/cards-layout/assets/ha-header-house.png');
            background-color: #366484; color: #FFFFFF;
        page:
          title: Übersicht
          icon: 'mdi:view-agenda'
          iconcolor: '#FFFFFF'
          description: Austellung Stromverbrauchsdaten - Messung Smartmeter
          width: 95%
          style: >-
            color: #FFFFFF; background: linear-gradient(to bottom, #366484,
            #182848);
        content:
          - row:
              - columns: null
                width: 100%
                icon: 'mdi:counter'
                title: Stromzähler Anzeige
                description: >-
                  Anzeige des Hoch- und Niedertarifes für den Überschuss und
                  Verbrauch der Energie. Aktueller Status des Stromzählers.
                entities:
                  - type: 'custom:simple-card'
                    mode: buttons
                    entities:
                      - entity: sensor.energy_consumption_meter_ht
                        name: HT-Tarif 1.8.1
                      - entity: sensor.energy_consumption_meter_nt
                        name: NT-Tarif 1.8.2
                      - entity: sensor.energy_production_meter_t1
                        name: HT-Tarif 2.8.1
                      - entity: sensor.energy_production_meter_t2
                        name: NT-Tarif 2.8.2
                      - entity: sensor.mt174_status
                        name: Uhrzeit
                      - entity: sensor.energy_notused
                        name: Energie ungenützt
                      - entity: sensor.energy_netto_ratio
                        name: Energienutzung
          - row:
              - columns: null
                width: 100%
                icon: 'mdi:counter'
                title: Auswertung Photovoltaik Leistung
                description: >-
                  Auswertung Photovoltaik Ertrag (Produktion bei
                  Sonnenlichtanteil).
                entities:
                  - type: 'custom:chart-card'
                    title: Photovoltaik Ertrag
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    debug: true
                    datascales:
                      mode: time
                    chartOptions:
                      plugins:
                        legend:
                          position: top
                          display: true
                        scales:
                          x:
                            title:
                              display: true
                              text: Solar-Energie
                          left:
                            title:
                              display: true
                              text: kWh
                          right:
                            title:
                              display: true
                              text: Lux
                            gridLines:
                              drawOnChartArea: false
                    entities:
                      - entity: sensor.date_time
                        dataid: kostalWh
                        unit: kWh
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=home_assistant&epoch=ms
                          query: >-
                            SELECT sum("value")*0.001 FROM "Wh" WHERE
                            ("entity_id" = 'kostal_watt_aktuell') AND time >
                            now() -240d GROUP BY time(1d) fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Photovoltaik
                        style:
                          yAxisID: left
                          backgroundColor: 'rgb(243, 180, 53,0.75)'
                      - entity: sensor.date_time
                        dataid: lux
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=home_assistant&epoch=ms
                          query: >-
                            SELECT mean("value") FROM "Lux" WHERE time > now()
                            -240d GROUP BY time(1d) fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Sonnenlicht
                        unit: Lux
                        style:
                          type: line
                          yAxisID: right
                          backgroundColor: 'rgba(233, 227, 144)'
                          fill: true
                          borderWidth: 1
          - row:
              - columns: null
                width: 100%
                icon: 'mdi:counter'
                title: Aktuelle Produktion vs. Überschuss
                description: >-
                  Aktuelle Anzeige des Hoch- und Niedertarifes für der
                  Produktion und Verbrauch der Energie.
                entities:
                  - type: 'custom:chart-card'
                    title: Energie Überschuss und Verbrauch
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    showstate: true
                    update_interval: 30
                    datascales:
                      range: 744
                      unit: hour
                      mode: time
                    showdetails:
                      title: Detaildaten Energie
                      title_sensor: Tarif
                      title_mean: Durchschnitt
                      title_min: Kleinster Wert
                      title_max: Größter Wert
                      title_current: Aktuell
                      title_timestamp: Aktualisiert am
                      visible: true
                    chartOptions:
                      plugins:
                        legend:
                          display: true
                      scales:
                        x:
                          alignToPixels: true
                          stacked: true
                          grid:
                            display: true
                            color: transparent
                            drawTicks: true
                            tickColor: '#f2c404'
                          ticks:
                            major:
                              enabled: true
                        'y':
                          title:
                            display: true
                            text: Produktion kWh
                    entities:
                      - entity: sensor.energy_production_t1
                        name: Überschuss HT
                        unit: kWh
                        factor: 1
                        aggregate: sum
                        style:
                          backgroundColor: '#f2c404'
                      - entity: sensor.energy_production_t2
                        name: Übeschuss NT
                        unit: kWh
                        factor: 1
                        aggregate: sum
                        style:
                          backgroundColor: '#e6bf61'
                      - entity: sensor.energy_consumption_ht
                        name: Verbrauch HT
                        unit: kWh
                        factor: -1
                        aggregate: sum
                        style:
                          backgroundColor: '#f04633'
                      - entity: sensor.energy_consumption_nt
                        name: Verbrauch NT
                        unit: kWh
                        ignoreZero: true
                        factor: -1
                        aggregate: sum
                        style:
                          backgroundColor: '#f67166'
          - row:
              - columns: null
                width: 50%
                entities:
                  - type: 'custom:simple-card'
                    subtitle: Aktuelle Einspeisung
                    mode: buttons
                    entities:
                      - entity: sensor.energy_production_t1
                        name: Überschuss HT
                      - entity: sensor.energy_production_t2
                        name: Überschuss NT
                      - entity: sensor.energy_production
                        name: Überschuss
                  - type: 'custom:simple-card'
                    subtitle: Aktueller Bezug
                    mode: buttons
                    entities:
                      - entity: sensor.energy_consumption_ht
                        name: Verbrauch HT
                      - entity: sensor.energy_consumption_nt
                        name: Verbrauch NT
                      - entity: sensor.energy_consumption
                        name: Verbrauch
          - row:
              - columns: null
                width: 100%
                title: 'Aktuelle Energieausnützung, Produktion & Verbrauch'
                description: >-
                  Auswertung der Energieausnützung (Frei vergügbar bzw.
                  ungenützt), Energieproduktion der Photovoltaikanlage,
                  Verbrauch gesamt für den definierten Zeitraum.
                entities:
                  - type: 'custom:chart-card'
                    title: Verfügbar
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    showstate: true
                    update_interval: 30
                    debug: true
                    datascales:
                      range: 12
                      unit: second
                      mode: category
                      ignoreZero: true
                    chartOptions:
                      plugins:
                        legend:
                          display: true
                          position: top
                      scales:
                        x:
                          alignToPixels: true
                          grid:
                            display: true
                            color: transparent
                            drawTicks: true
                            tickColor: '#f2c404'
                        left:
                          title:
                            display: true
                            text: kWh
                            color: '#d9534f'
                          ticks:
                            autoSkip: true
                            maxTicksLimit: 12
                        right:
                          title:
                            display: true
                            text: Ausschöpfung %
                            color: 'rgb(59, 179, 195)'
                          gridLines:
                            drawOnChartArea: false
                    entities:
                      - entity: sensor.energy_production
                        name: Verfügbar
                        unit: kw
                        ignoreZero: true
                        factor: 1
                        aggregate: max
                        style:
                          yAxisID: left
                          fill: true
                          gradient:
                            colors:
                              - '#d9534f'
                              - '#fd5217'
                              - '#ff0000'
                      - entity: sensor.energy_netto_ratio
                        name: Ausschöpfung
                        style:
                          type: line
                          fill: true
                          yAxisID: right
                          backgroundColor: 'rgba(59, 179, 195,0.25)'
                          borderColor: 'rgba(59, 179, 195,0.75)'
                          borderWidth: 1
          - row:
              - columns: null
                width: 50%
                entities:
                  - type: 'custom:chart-card'
                    title: Produktion
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    showstate: false
                    update_interval: 30
                    datascales:
                      range: 744
                      unit: hour
                      mode: time
                    showdetails:
                      title: Detaildaten Produktion
                      title_sensor: Kostal
                      title_min: Kleinster Wert
                      title_max: Größter Wert
                      visible: true
                    chartOptions:
                      plugins:
                        legend:
                          display: false
                      scales:
                        x:
                          alignToPixels: true
                          grid:
                            display: true
                            color: transparent
                            drawTicks: true
                            tickColor: '#f2c404'
                        'y':
                          title:
                            display: true
                            text: Produktion kWh
                            color: '#fcec34'
                    entities:
                      - entity: sensor.kostal_watt_aktuell
                        name: Energieproduktion
                        unit: kWh
                        ignoreZero: true
                        factor: 0.001
                        aggregate: max
                        style:
                          backgroundColor: '#fcec34'
                  - type: 'custom:chart-card'
                    title: Verbrauch
                    icon: 'mdi:counter'
                    height: 360
                    chart: bar
                    showstate: false
                    update_interval: 30
                    datascales:
                      range: 744
                      unit: hour
                      mode: time
                    showdetails:
                      title: Detaildaten Verbrauch
                      title_sensor: Gesamt
                      title_min: Kleinster Wert
                      title_max: Größter Wert
                      visible: true
                    chartOptions:
                      plugins:
                        legend:
                          display: false
                      scales:
                        x:
                          alignToPixels: true
                          grid:
                            display: true
                            color: transparent
                            drawTicks: true
                            tickColor: '#f2c404'
                        'y':
                          title:
                            display: true
                            text: Verbrauch kWh
                            color: '#FF8066'
                    entities:
                      - entity: sensor.verbrauch_gesamt
                        name: Verbrauch
                        unit: kWh
                        ignoreZero: true
                        factor: 0.01
                        aggregate: max
                        style:
                          backgroundColor: '#FF8066'
          - row:
              - columns: null
                width: 50%
                icon: 'mdi:counter'
                entities:
                  - type: 'custom:simple-card'
                    mode: buttons
                    subtitle: Überschuss pro Tag
                    entities:
                      - entity: sensor.energy_production_day_t1
                        name: Produktion HT
                      - entity: sensor.energy_production_day_t2
                        name: Produktion NT
                      - entity: sensor.energy_production_day
                        name: Produktion
                  - type: 'custom:simple-card'
                    mode: buttons
                    subtitle: Verbrauch pro Tag
                    entities:
                      - entity: sensor.energy_consumption_day_ht
                        name: Verbrauch HT
                      - entity: sensor.energy_consumption_day_nt
                        name: Verbrauch NT
                      - entity: sensor.energy_consumption_day
                        name: Verbrauch
          - row:
              - columns: null
                width: 50%
                title: null
                entities:
                  - type: 'custom:simple-card'
                    subtitle: Überschuss pro Monat
                    mode: buttons
                    entities:
                      - entity: sensor.energy_production_month_t1
                        name: Überschuss HT
                      - entity: sensor.energy_production_month_t2
                        name: Überschuss NT
                      - entity: sensor.energy_production_month
                        name: Überschuss
                  - type: 'custom:simple-card'
                    subtitle: Verbrauch pro Monat
                    mode: buttons
                    entities:
                      - entity: sensor.energy_consumption_month_ht
                        name: Verbrauch HT
                      - entity: sensor.energy_consumption_month_nt
                        name: Verbrauch NT
                      - entity: sensor.energy_consumption_month
                        name: Verbrauch
              - columns: null
                width: 50%
                title: null
                entities:
                  - type: 'custom:simple-card'
                    subtitle: Überschuss pro Jahr
                    mode: buttons
                    entities:
                      - entity: sensor.energy_production_year_t1
                        name: Überschuss HT
                      - entity: sensor.energy_production_year_t2
                        name: Überschuss NT
                      - entity: sensor.energy_production_year
                        name: Überschuss
                  - type: 'custom:simple-card'
                    subtitle: Verbrauch pro Jahr
                    mode: buttons
                    entities:
                      - entity: sensor.energy_consumption_year_ht
                        name: Verbrauch HT
                      - entity: sensor.energy_consumption_year_nt
                        name: Verbrauch NT
                      - entity: sensor.energy_consumption_year
                        name: Verbrauch
