views:
  - id: testcharts
    icon: 'mdi:ab-testing'
    panel: true
    path: testcharts
    cards:
      - type: 'custom:cards-layout'
        toolbar:
          backgroundcolor: '#5CD5FE'
          iconcolor: '#047CD1'
          visible: true
        header:
          title: Fitness
          icon: 'mdi:nutrition'
          iconcolor: '#FFFFFF'
          style: >-
            background-image:
            url('/hacsfiles/cards-layout/assets/ha-header-fitness2.png');
            background-color: #5CD5FE !important; color: #047CD1;
        page:
          title: Informationen über Körperwerte
          icon: 'mdi:tape-measure'
          icon_color: '#FFFFFF'
          description: |
            Verschiedene Grafiken über die Ernährung und Körperwerte
            <ul>
              <li>Makronährstoffe</li>
              <li>Körperwerte (Messung MI Bodyscale II</li>
              <li>Vergeichswert Ergebnisse</li> 
            </ul>
            <br/>
          style: >-
            color:#FFFFFF; background: linear-gradient(to top, #2A9CF2,
            #007ACF);
          width: 90%
        content:
          - row:
              - column: null
                width: 100%
                entities:
                  - type: 'custom:chart-card'
                    title: Gewicht & Fettfreie Masse
                    icon: 'mdi:counter'
                    height: 360
                    chart: line
                    debug: true
                    update_interval: 600
                    datascales:
                      mode: time
                    chartOptions:
                      plugins:
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          alignToPixels: true
                          title:
                            text: Zeitraum 6 Monate
                            display: true
                          grid:
                            display: false
                        'y':
                          title:
                            display: true
                            text: kg
                    entities:
                      - entity: sensor.date_time
                        dataid: gewicht
                        unit: kg
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=historydata&epoch=ms
                          query: >-
                            SELECT mean("weight") FROM "miscale_peter" WHERE
                            time > now() -180d GROUP BY time(1d) fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Gewicht
                        style:
                          backgroundColor: 'rgba(2, 117, 216,0.70)'
                          fill: true
                          borderWidth: 1
                          order: 1
                      - entity: sensor.date_time
                        dataid: fettmasse
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=historydata&epoch=ms
                          query: >-
                            SELECT mean("lbm") FROM "miscale_peter" WHERE time >
                            now() -180d GROUP BY time(1d)  fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Fettfreie Masse
                        unit: kg
                        style:
                          backgroundColor: 'rgba(217, 83, 79, 0.90)'
                          fill: true
                          borderWidth: 1
                          order: 0
                  - type: 'custom:chart-card'
                    title: Zusammenfassung der Ergebnisse
                    icon: 'mdi:scale'
                    height: 360
                    chart: line
                    datascales:
                      range: 92
                      unit: day
                      mode: time
                      aggregate: max
                      ignoreZero: true
                    showstate: true
                    showdetails:
                      title: Zusammenfassung
                      title_sensor: Ergebnis
                      title_mean: Durchschnitt
                      title_min: Kleinster Wert
                      title_max: Größter Wert
                      title_current: Aktuell
                      title_timestamp: Aktualisiert am
                      visible: true
                    options:
                      plugins:
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          title:
                            display: true
                            text: Zeitraum
                        left:
                          title:
                            display: true
                            text: Gewicht / Muskeln
                          ticks:
                            autoSkip: true
                            maxTicksLimit: 12
                        right:
                          title:
                            display: true
                            text: BMI
                          gridLines:
                            drawOnChartArea: false
                          ticks:
                            autoSkip: true
                            maxTicksLimit: 16
                    entities:
                      - entity: sensor.peter_muskeln
                        style:
                          yAxisID: left
                          type: line
                          backgroundColor: 'rgb(241,196,15)'
                          borderColor: 'rgb(241,196,15)'
                      - entity: sensor.peter_gewicht
                        unit: kg
                        style:
                          yAxisID: left
                          type: line
                          backgroundColor: '#03a9f4'
                          borderColor: '#03a9f4'
                      - entity: sensor.peter_bmi
                        unit: kg/m²
                        style:
                          yAxisID: right
                          type: bar
                          fill: true
                          gradient:
                            colors:
                              - '#e74c3c'
                              - '#ff5722'
                              - '#ff9500'
          - row:
              - columns: null
                width: 50%
                entities:
                  - type: 'custom:chart-card'
                    title: Makro Nährstoffe
                    icon: 'mdi:nutrition'
                    chart: bar
                    height: 320
                    chartOptions:
                      segmented: true
                      plugins:
                        title:
                          display: true
                          text: Aufteilung Nährstoffe (kal) pro Tag
                      scales:
                        'y':
                          title:
                            display: true
                            text: Kalorien
                    entities:
                      - options:
                          unit: kal
                      - entity: sensor.peter_eiweis_makronahrstoff
                        name: Eiweis
                        style:
                          backgroundColor: '#f1c40f'
                      - entity: sensor.peter_fett_makronahrstoff
                        name: Fett
                        style:
                          backgroundColor: '#e74c3c'
                      - entity: sensor.peter_kohlenhydrate_makronahrstoff
                        name: Kohlenhydrate
                        style:
                          backgroundColor: '#009688'
                  - type: 'custom:chart-card'
                    title: Aktuelle Körperwerte
                    icon: 'mdi:weight-lifter'
                    height: 320
                    chart: radar
                    chartOptions:
                      plugins:
                        title:
                          text: Aktuelle Werte
                      scales:
                        r:
                          grid:
                            color:
                              - '#03a9f4'
                              - '#00bcd4'
                              - '#8bc34a'
                              - '#e51400'
                              - '#cddc39'
                              - '#ff9800'
                              - '#ff5722'
                          angleLines:
                            display: true
                            color: '#5ac8fa'
                    entities:
                      - entity: sensor.peter_koperfett
                        name: Fett
                        unit: '%'
                      - entity: sensor.peter_korperwasser
                        name: Wasser
                        unit: '%'
                      - entity: sensor.peter_muskeln
                        name: Muskeln
                        unit: '%'
                      - entity: sensor.peter_fettfreie_korpermasse
                        name: Fettfreie Masse
                        unit: '%'
                      - entity: sensor.peter_gewicht
                        name: Gewicht
                        unit: kg
                      - entity: sensor.peter_viszerales_fett
                        name: Viszerales Fett
                        unit: '%'
          - row:
              - columns: null
                width: 100%
                entities:
                  - type: 'custom:chart-card'
                    title: Änderungen zum Vortag
                    icon: 'mdi:tape-measure'
                    height: 360
                    datascales:
                      range: 200
                      unit: day
                      mode: time
                      ignoreZero: true
                    chart: bar
                    options:
                      plugins:
                        title:
                          text: Abweichungen zum Vortag
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          stacked: true
                        'y':
                          stacked: true
                          title:
                            display: true
                            text: Abweichung in %
                    entities:
                      - options:
                          unit: '%'
                      - entity: sensor.peter_trend_fett
                        name: Fett
                        aggregate: max
                      - entity: sensor.peter_trend_gewicht
                        name: Gewicht
                        aggregate: max
                      - entity: sensor.peter_trend_muskeln
                        name: Muskeln
                        aggregate: max
                      - entity: sensor.peter_trend_wasser
                        name: Wasser
                        aggregate: max
          - row:
              - columns: null
                width: 50%
                entities:
                  - type: 'custom:chart-card'
                    title: Vergleich Muskeln vs. Fett
                    icon: 'mdi:tape-measure'
                    height: 360
                    datascales:
                      range: 120
                      unit: day
                    chart: bubble
                    options:
                      plugins:
                        title:
                          text: Verhältnis BMI zu Muskeln/Fett
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          min: 8
                          max: 18
                        'y':
                          min: 30
                          max: 70
                    entities:
                      - entity: sensor.peter_koperfett
                        name: Fett
                        unit: '%'
                      - entity: sensor.peter_muskeln
                        name: Muskeln
                        unit: '%'
                      - entity: sensor.peter_bmi
                        name: BMI Peter
                        scale: 0.5
                        unit: kg
                        style:
                          backgroundColor: 'rgb(52,152,219)'
                      - entity: sensor.reni_koperfett
                        name: Fett
                        unit: '%'
                      - entity: sensor.reni_muskeln
                        name: Muskeln
                        unit: '%'
                      - entity: sensor.reni_bmi
                        name: BMI Reni
                        scale: 0.5
                        unit: kg
                        style:
                          backgroundColor: 'rgb(255,152,219)'
                  - type: 'custom:chart-card'
                    title: Vergleich Körperfett % vs. BMI kg/m²
                    icon: 'mdi:tape-measure'
                    height: 360
                    datascales:
                      range: 120
                      unit: day
                    chart: scatter
                    options:
                      plugins:
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          title:
                            display: true
                            text: Fettgehalt (%)
                        'y':
                          title:
                            display: true
                            text: BMI kg/m²
                    entities:
                      - entity: sensor.reni_koperfett
                        name: Reni
                        aggregate: max
                        unit: '%'
                      - entity: sensor.reni_bmi
                        aggregate: max
                      - entity: sensor.peter_koperfett
                        name: Peter
                        aggregate: max
                        unit: kg/m²
                      - entity: sensor.peter_bmi
                        aggregate: max
                  - type: 'custom:chart-card'
                    title: Körperfett Anteile
                    icon: 'mdi:counter'
                    height: 360
                    chart: line
                    debug: true
                    update_interval: 600
                    datascales:
                      mode: time
                    chartOptions:
                      plugins:
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          alignToPixels: true
                          title:
                            text: Zeitraum 30 Tage
                            display: true
                          grid:
                            display: false
                        'y':
                          title:
                            display: true
                            text: '% Anteil'
                    entities:
                      - entity: sensor.date_time
                        dataid: bodyfat
                        unit: '%'
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=historydata&epoch=ms
                          query: >-
                            SELECT mean("fat") FROM "miscale_peter" WHERE time >
                            now() -30d GROUP BY time(1d) fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Körperfett
                        style:
                          backgroundColor: 'rgba(239, 90,40,0.70)'
                          fill: true
                          borderWidth: 1
                          order: 1
                      - entity: sensor.date_time
                        dataid: visceral
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=historydata&epoch=ms
                          query: >-
                            SELECT mean("visceral") FROM "miscale_peter" WHERE
                            time > now() -30d GROUP BY time(1d)  fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Viszerales Fett
                        unit: '%'
                        style:
                          backgroundColor: 'rgba(254, 115, 131, 0.90)'
                          fill: true
                          borderWidth: 1
                          order: 0
                  - type: 'custom:chart-card'
                    title: Muskeln / Eiweis
                    icon: 'mdi:counter'
                    height: 360
                    chart: line
                    debug: true
                    update_interval: 600
                    datascales:
                      mode: time
                    chartOptions:
                      plugins:
                        legend:
                          position: top
                          display: true
                      scales:
                        x:
                          alignToPixels: true
                          title:
                            text: Zeitraum 30 Tage
                            display: true
                          grid:
                            display: false
                        'y':
                          title:
                            display: true
                            text: '% Anteil'
                    entities:
                      - entity: sensor.date_time
                        dataid: muscle
                        unit: '%'
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=historydata&epoch=ms
                          query: >-
                            SELECT mean("muscle") FROM "miscale_peter" WHERE
                            time > now() -30d GROUP BY time(1d) fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Muskeln
                        style:
                          backgroundColor: 'rgba(250, 135,20,0.70)'
                          fill: true
                          borderWidth: 1
                          order: 1
                      - entity: sensor.date_time
                        dataid: visceral
                        datasource:
                          influxdb: >-
                            https://influxdb.local/query?db=historydata&epoch=ms
                          query: >-
                            SELECT mean("protein") FROM "miscale_peter" WHERE
                            time > now() -30d GROUP BY time(1d)  fill(null)
                          token: YWRtaWdAYmVlcDRCb3Nz
                        name: Eiweis
                        unit: '%'
                        style:
                          backgroundColor: 'rgba(234, 184, 57, 0.90)'
                          fill: true
                          borderWidth: 1
                          order: 0
